app_user_info/urls.py
from django.urls import path
from app_user_info import views

app_name = 'app_user_info'

urlpatterns = [
    path('', views.division_view.as_view(), name='home_view'),
    path('districts/', views.district_view.as_view(), name='district_view'),
    path('upazillas/', views.upazilla_view.as_view(), name='upazilla_view'),
    path('users/', views.users_view, name='users'),
    path('search_user/', views.search_user_view, name='search_user'),
]

odelltech_task/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_user_info.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

app_user_info/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Divisions(models.Model):
    name = models.CharField(max_length=255)
    country = models.ForeignKey(Country,on_delete=models.CASCADE,related_name='divisions')

    def __str__(self):
        return self.name

class Districts(models.Model):
    name = models.CharField(max_length=255)
    division = models.ForeignKey(Divisions,on_delete=models.CASCADE,related_name='zila')

    def __str__(self):
        return self.name


class Upazilla(models.Model):
    name = models.CharField(max_length=255)
    district = models.ForeignKey(Districts,on_delete=models.CASCADE,related_name='thana')
    
    def __str__(self):
        return self.name


class User_info(models.Model):
    name = models.CharField(max_length=255)
    country = models.ForeignKey(Country,on_delete=models.SET_NULL,blank=True,null=True,related_name='cntry')
    Division = models.ForeignKey(Divisions,on_delete=models.SET_NULL,blank=True,null=True,related_name='dvsn')
    District = models.ForeignKey(Districts,on_delete=models.SET_NULL,blank=True,null=True,related_name='dstrct')
    upazilla = models.ForeignKey(Upazilla,on_delete=models.SET_NULL,blank=True,null=True,related_name='upzla')

    def __str__(self):
        return self.name

app_user_info/forms.py
from django import forms
from app_user_info import models

class user_info_form(forms.ModelForm):
    # name = forms.CharField(required=True, label="",widget=forms.TextInput(attrs={'placeholder':'Full Name','class':'mb-2'}))
    # country = forms.ForeignKeyField(required=True, label="",widget=forms.TextInput(attrs={'placeholder':'Last Name','class':'mb-2'}))
    # email = forms.EmailField(required=True, label="",widget=forms.TextInput(attrs={'placeholder':'Email','class':'mb-2'}))
    # username = forms.CharField(required=True, label="",widget=forms.TextInput(attrs={'placeholder':'Username','class':'mb-2'}))
    # password1 = forms.CharField(required=True, label="",widget=forms.PasswordInput(attrs={'placeholder':'Password','class':'mb-2'}))
    # password2 = forms.CharField(required=True, label="",widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password','class':'mb-2'}))
    class Meta:
        model = models.User_info
        fields = ('name','country','Division','District','upazilla')
        

app_user_info/views.py
from django.contrib.auth import forms
from django.http.response import JsonResponse
from django.shortcuts import render,HttpResponseRedirect,redirect
from app_user_info import models
from app_user_info import forms
from django.urls import reverse,reverse_lazy
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from django.db.models import Q


# Create your views here.
class division_view(APIView):
    # permission_classes = [IsAuthenticated,]
    def get(self,request):
        form = forms.user_info_form()
        diction = {'form':form}
        return render(request,'app_user_info/home.html',context=diction)
        
    
    def post(self,request,format=None):
        country = request.data['country'] # name of the Divisions tables foreignkey
        division = {}
        # div = request.POST.get['Division']
        # dis = request.POST.get['District']
        # upz = request.POST.get[]
        form = forms.user_info_form(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app_user_info:home_view'))
        
        if country:
            divisions = models.Country.objects.get(id=country).divisions.all()
            division = {p.name:p.id for p in divisions}
        return JsonResponse(data=division,safe=False)

class district_view(APIView):
    # permission_classes = [IsAuthenticated,]
    
    def post(self,request,format=None):
        division = request.data['division'] # name of the District tables foreignkey
        district = {}
        if division:
            districts = models.Divisions.objects.get(id=division).zila.all()
            district = {p.name:p.id for p in districts}
        return JsonResponse(data=district,safe=False)


class upazilla_view(APIView):
    # permission_classes = [IsAuthenticated,]
    
    def post(self,request,format=None):
        district = request.data['district'] # name of the upazila tables foreignkey
        upazilla = {}
        if district:
            upazillas = models.Districts.objects.get(id=district).thana.all()
            upazilla = {p.name:p.id for p in upazillas}
        return JsonResponse(data=upazilla,safe=False)

def users_view(request):
    all_user = models.User_info.objects.all()
    diction = {'all_user':all_user}
    return render(request,'app_user_info/users.html',context=diction)


def search_user_view(request):
     if request.method == 'GET':
        pattern = request.GET.get('search','')
        result = models.User_info.objects.filter(Q(name__icontains=pattern))
        diction = {'result':result,'pattern':pattern}
        return render(request,'app_user_info/search_user.html',context=diction)

templates/app_user_info/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    Home
{% endblock title_block %}


{% block body_block %}
    <div class="row mt-5">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="row mt-5">
                <div class="col-md-2"></div>
                <div class="col-md-8 text-center">
                    <div class="card" style="width: 27rem;">
                        
                        <div class="card-body">
                          <form action="" method="POST">
                              {{ form|crispy }}
                              {% csrf_token %}
                              <input type="submit" name="submit" value="Submit" class="form-control mt-4 btn btn-success">
                          </form>
                        </div>
                    </div>
                    
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>


{% endblock body_block %}

templates/app_user_info/search_user.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %}
    Home
{% endblock title_block %}

{% block body_block %}
  
    <div class="row mt-4">
        {% if pattern %}
                <div class="card mb-3" style="max-width: 540px;">
                    {% for data in result %}
                    <div class="row g-0">
                        <div class="col-md-10">
                            <div class="card-body">
                                <h5 class="card-title">{{ data.name }}</h5>
                                <p class="card-text">Country: <b>{{ data.country}} </b><br>
                                Division: <b>{{ data.Division}} </b></p>
                            </div>
                        </div>
                    </div>
                    <hr>
                    {% endfor %}
                </div>
            
        {% endif %}
    </div>
{% endblock body_block %}

templates/app_user_info/users.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %}
    Users
{% endblock title_block %}

{% block nav_block %}
    <li class="nav-item" style="padding-right: 30px">
              <a
                class="nav-link"
                aria-current="page"
                href="{% url 'app_user_info:home_view' %}"
                ><i class="fa fa-home fa-fw" aria-hidden="true"></i> Home</a
              >
            </li>
            <li class="nav-item" style="padding-right: 30px">
              <a class="nav-link active" href="{% url 'app_user_info:users' %}"
                ><i class="fa fa-user fa-fw" aria-hidden="true"></i> Users</a
              >
            </li>
{% endblock nav_block %}

{% block body_block %}
  
    <div class="row mt-3 text-center">
        <div class="col-md-10  mx-auto mt-3">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Country</th>
                <th scope="col">Division</th>
                <th scope="col">District</th>
                <th scope="col">Upazilla</th>
              </tr>
            </thead>
            <tbody>
            {% for user in all_user %}
              <tr>
                
                <td>{{user.name}}</td>
                <td>{{user.country}}</td>
                <td>{{user.Division}}</td>
                <td>{{user.District}}</td>
                <td>{{user.upazilla}}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
    </div>
{% endblock body_block %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <!-- <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet"> -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>{% block title_block %} {% endblock title_block %}</title>
  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark sticky-top"
      style="background: #0e1d3b"
    >
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Odelltech</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            {% block nav_block %} 
            <li class="nav-item" style="padding-right: 30px">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'app_user_info:home_view' %}"
                ><i class="fa fa-home fa-fw" aria-hidden="true"></i> Home</a
              >
            </li>
            <li class="nav-item" style="padding-right: 30px">
              <a class="nav-link" href="{% url 'app_user_info:users' %}"
                ><i class="fa fa-user fa-fw" aria-hidden="true"></i> Users</a
              >
            </li>

            {% endblock nav_block %}
          </ul>
          <form
            class="d-flex"
            method="GET"
            action="{% url 'app_user_info:search_user' %}"
          >
            <input type="Search" class="form-control me-2" name="search" />
            <input
              class="btn btn-outline-success"
              type="submit"
              value="Search Users"
            />
          </form>
        </div>
      </div>
      <hr />
    </nav>

    <div class="container mt-4">
      {% block body_block %} {% endblock body_block %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/ajax.js' %}" type="text/javascript"></script>
    <script>
      baguetteBox.run(".tz-gallery");
    </script>
    {% block script_blog %} {% endblock script_blog %}

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>